In [1]:
import numpy as np
import pandas as pd

print(f"Numpy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")
np.set_printoptions(precision=2)

Numpy version: 2.4.4
Pandas version: 3.0.2


In [2]:
array1 = np.array([[1, 2, 3, 4, 5, 6]])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

print(
    f"1D Array:\n{array1}\n"
    f"Rows: {array1.shape[0] if array1.ndim >= 1 else 0}\n"
    f"Columns: {array1.shape[1] if array1.ndim >= 2 else 0}\n"
    f"Data Type: {array1.dtype}\n"
)

print(
    f"2D Array:\n{array2}\n"
    f"Rows: {array2.shape[0] if array2.ndim >= 1 else 0}\n"
    f"Columns: {array2.shape[1] if array2.ndim >= 2 else 0}\n"
    f"Data Type: {array2.dtype}"
)

1D Array:
[[1 2 3 4 5 6]]
Rows: 1
Columns: 6
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]]
Rows: 2
Columns: 3
Data Type: int64


In [3]:
zero_array = np.zeros((3, 4))
ones_array = np.ones((2, 3))
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 10)

print(f"Zeros array:\n{zero_array}\n")
print(f"Ones array:\n{ones_array}\n")
print(f"Range array: {range_array}\n")
print(f"Linspace array: {linspace_array}\n")

Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]

Range array: [0 2 4 6 8]

Linspace array: [0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]



In [4]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

print(f"Addition: {a+b}\n")
print(f"Multiplication: {a*b}\n")
print(f"Power: {a**2} & {b**2}\n")
print(f"Square Root: {np.sqrt(a)} & {np.sqrt(b)}\n")

print(f"Mean: {np.mean(a)} & {np.mean(b)}\n")
print(f"Standard Deviation: {round(np.std(a), 2)} & {round(np.std(b), 2)}\n")
print(f"Min: {np.min(a)} & {np.min(b)}\n")
print(f"Max: {np.max(a)} & {np.max(b)}")

Addition: [ 3  7 11 15 19]

Multiplication: [ 2 12 30 56 90]

Power: [ 1  9 25 49 81] & [  4  16  36  64 100]

Square Root: [1.   1.73 2.24 2.65 3.  ] & [1.41 2.   2.45 2.83 3.16]

Mean: 5.0 & 6.0

Standard Deviation: 2.83 & 2.83

Min: 1 & 2

Max: 9 & 10


In [5]:
matrix = np.array([[1, 5, 9], [3, 5, 7]])
vector = np.array([2, 5, 8])
broad_casting = matrix + vector
print(f"Broadcasting result:\n{broad_casting}")

Broadcasting result:
[[ 3 10 17]
 [ 5 10 15]]
